version : '2'

services:
  service:
    image: daniellavoie/confluent-microservices-wallet:${WALLET_VERSION}
    restart: always
    mem_limit: 1g
    networks:
    - traefik
    - default
    labels:
    - "traefik.backend=it.wallet.confluent.daniellavoie.dev"
    - "traefik.frontend.rule=Host:it.wallet.confluent.daniellavoie.dev"
    - "traefik.port=80"
    - "traefik.docker.network=traefik_webgateway"
    environment:
      SPRING_PROFILES_ACTIVE: ccloud
      CCLOUD_BOOTSTRAPSERVERS: ${CCLOUD_BOOTSTRAP_SERVERS}
      CCLOUD_API_KEY: ${CCLOUD_API_KEY}
      CCLOUD_API_SECRET: ${CCLOUD_API_SECRET}
      WALLET_TOPICS_TRANSACTIONSUCCESS_NAME: wallet-it-transaction-success
      WALLET_TOPICS_WALLET_NAME: wallet-it-wallet
      WALLET_TOPICS_ACCOUNT_NAME: wallet-it-account

networks:
  traefik:
    external:
      name: traefik_webgateway
