---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: springcloudservices/spring-cloud-base

inputs:
- name: ci

run:
  path: ci/ci/tasks/connector/delete-connector.sh

params:
  CONNECT_URL:
  CONNECTOR_NAME: