---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: springcloudservices/spring-cloud-base

inputs:
- name: ci
- name: deploy
- name: rate-version
- name: transaction-version
- name: wallet-version
- name: ui-version
- name: data-faker-version

run:
  path: ci/ci/tasks/deploy/undeploy-docker-compose.sh

params:
  DEPLOYMENT_NAME:
  DOCKER_HOSTNAME:
  DOCKER_SSH_USER:
  DOCKER_SSH_PRIVATE_KEY:
  DOCKER_COMPOSE_FILE: 
  REGISTRY_URL:
  REGISTRY_USERNAME:
  REGISTRY_PASSWORD:
  CCLOUD_BOOTSTRAPSERVERS:
  CCLOUD_API_KEY: 
  CCLOUD_API_SECRET: 