---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: microservices-dev-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: microservices-dev-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluent/schema-registry
    container_name: microservices-dev-sr
    restart: always
    depends_on:
    - kafka
    - zookeeper
    ports:
    - 9090:8081
    environment:
      SR_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"

  account-db:
    container_name: microservices-dev-account-db
    image: mysql
    ports:
    - 3306:3306
    environment:
      - MYSQL_USER=account-store
      - MYSQL_PASSWORD=account-store
      - MYSQL_DATABASE=account-store
      - MYSQL_ROOT_PASSWORD=account-store