---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: springcloudservices/spring-cloud-base

inputs:
- name: ci
- name: deploy
- name: rate-version

run:
  path: ci/ci/tasks/deploy/deploy-docker-compose.sh

params:
  DEPLOYMENT_NAME:
  DOCKER_HOSTNAME:
  DOCKER_SSH_USER:
  DOCKER_SSH_PRIVATE_KEY:
  DOCKER_COMPOSE_FILE: 
  REGISTRY_URL:
  REGISTRY_USERNAME:
  REGISTRY_PASSWORD:
  CCLOUD_BOOTSTRAP_SERVERS:
  CCLOUD_API_KEY:
  CCLOUD_API_SECRET:
  SCHEMA_REGISTRY_URL:
  SCHEMA_REGISTRY_KEY:
  SCHEMA_REGISTRY_SECRET: